title: Bryan Eikema
# email: b.eikema@uva.nl
# description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: bryaneikema
# github_username:  Roxot
locale: "en"

# Author information (sidebar)
author:
    name: "Bryan Eikema"
    avatar: "/assets/images/bio-photo.jpg"
    bio:  "PhD Student Natural Language Processing"
    # location: "University of Amsterdam"
    links:
        - label: "Twitter"
          icon: "fab fa-fw fa-twitter-square"
          url: "https://twitter.com/bryaneikema"
        - label: "GitHub"
          icon: "fab fa-fw fa-github"
          url: "https://github.com/roxot"
        - label: "b.eikema@uva.nl"
          icon: "far fa-envelope"
          url: "mailto:b.eikema@uva.nl"

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.15.2"
plugins:
  - jekyll-feed
  - jekyll-include-cache
